<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, onMounted, ref, watch } from "vue";
import { ask, err, isDemo, type AskResult, type Citation } from "./api";
import { askView } from "./ask-result";
import { assistantScope, type AssistantScope } from "./assistant-scope";
import { exportConversation, loadConversations, saveConversations, storageState, type Attachment, type Conversation, type ConversationMessage } from "./conversation-store";
const open=ref(false), historyOpen=ref(false), conversations=ref<Conversation[]>([]), activeId=ref(""), running=ref(false), status=ref(""), attachment=ref<Attachment>(), returnFocus=ref<HTMLElement>(), panelWidth=ref(420), historyWidth=ref(240), atBottom=ref(true);
const clone=(x:AssistantScope):AssistantScope=>({label:x.label,snapshot:x.snapshot,filters:{...x.filters}});
const activeScope=ref(clone(assistantScope)); let controller:AbortController|undefined, generation=0;
const active=computed(()=>conversations.value.find((item)=>item.id===activeId.value));
const draft=computed({get:()=>active.value?.draft||"",set:(value)=>{if(active.value){active.value.draft=value; active.value.updatedAt=Date.now(); persist();}}});
const messages=computed(()=>active.value?.messages||[]);
function id(){return crypto.randomUUID()}
function create(){const value:Conversation={id:id(),title:"新研究会话",draft:"",createdAt:Date.now(),updatedAt:Date.now(),messages:[]}; conversations.value=[value,...conversations.value];activeId.value=value.id;persist();}
function persist(){void saveConversations(conversations.value)}
function openPanel(event:Event){returnFocus.value=event.currentTarget as HTMLElement;if(!active.value)create();open.value=true;void nextTick(()=>document.querySelector<HTMLTextAreaElement>(".assistant-composer textarea")?.focus())}
function close(){controller?.abort();open.value=false;void nextTick(()=>returnFocus.value?.focus())}
function rename(){if(!active.value)return;const title=prompt("会话名称",active.value.title);if(title){active.value.title=title.trim()||active.value.title;persist()}}
function remove(){if(!active.value)return;conversations.value=conversations.value.filter(x=>x.id!==activeId.value);activeId.value=conversations.value[0]?.id||"";if(!active.value)create();persist()}
function exportActive(){if(!active.value)return;const blob=new Blob([exportConversation(active.value)],{type:"application/json"});const link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download=active.value.title+".json";link.click();URL.revokeObjectURL(link.href)}
function removeAttachment(){attachment.value=undefined}
function scrollBottom(){document.querySelector(".assistant-messages")?.scrollTo({top:999999,behavior:"smooth"});atBottom.value=true}
function addMessage(message:ConversationMessage){if(!active.value)return;active.value.messages.push(message);active.value.updatedAt=Date.now();persist()}
async function submit(){if(!active.value||!draft.value.trim()||running.value)return;const question=draft.value.trim(),scope=clone(activeScope.value),mode=isDemo()?"demo":"live",eventId=attachment.value?.id,current=++generation;draft.value="";const user:ConversationMessage={id:id(),role:"user",text:question,createdAt:Date.now(),scope:scope.snapshot,filters:scope.filters,mode,attachment:attachment.value};addMessage(user);attachment.value=undefined;running.value=true;status.value="正在检索并汇总…";const answer:ConversationMessage={id:id(),role:"assistant",text:"",createdAt:Date.now(),scope:scope.snapshot,mode,status:"running"};addMessage(answer);try{const history=active.value.messages.filter((item) => item.id !== user.id && item.status !== "running" && item.status !== "已取消，未自动重试。" && item.text).slice(-6).map((item) => ({ role:item.role, content:item.text.slice(0,4000), ...(item.role === "user" ? { filters:item.filters || scope.filters } : {}) })); const response=await ask({question,filters:scope.filters,timezone:"Asia/Shanghai",answer_mode:"concise",client_request_id:id(),history,event_ids:eventId ? [eventId] : undefined},(controller=new AbortController()).signal);if(current!==generation)return;const view=askView(response);answer.text=response.answer||"";answer.status=view.status;answer.citations=view.citations;status.value=view.status;persist()}catch(cause){if(current!==generation)return;answer.status=(cause as Error).name==="AbortError"?"已取消，未自动重试。":err(cause).code;answer.text=(cause as Error).name==="AbortError"?"":err(cause).message;status.value=answer.status;persist()}finally{if(current===generation)running.value=false}}
function cancel(){generation++;controller?.abort();running.value=false;status.value="已取消，未自动重试。"}
function resize(event:PointerEvent, target:"panel"|"history"){const start=event.clientX,initial=target==="panel"?panelWidth.value:historyWidth.value;const move=(e:PointerEvent)=>{const delta=start-e.clientX;if(target==="panel")panelWidth.value=Math.min(innerWidth*.5,Math.max(340,initial+delta));else historyWidth.value=Math.min(360,Math.max(180,initial-delta));localStorage.setItem(target==="panel"?"assistant-width":"history-width",String(target==="panel"?panelWidth.value:historyWidth.value));};const up=()=>{window.removeEventListener("pointermove",move);window.removeEventListener("pointerup",up)};window.addEventListener("pointermove",move);window.addEventListener("pointerup",up)}
function keyResize(event:KeyboardEvent,target:"panel"|"history"){if(!event.altKey||!["ArrowLeft","ArrowRight"].includes(event.key))return;event.preventDefault();const n=event.key==="ArrowLeft"?-20:20;if(target==="panel")panelWidth.value=Math.min(innerWidth*.5,Math.max(340,panelWidth.value+n));else historyWidth.value=Math.min(360,Math.max(180,historyWidth.value-n));}
const attach=(event:Event)=>{attachment.value=(event as CustomEvent<Attachment>).detail;open.value=true};
watch(assistantScope,(scope)=>{activeScope.value=clone(scope)},{deep:true});
onMounted(async()=>{panelWidth.value=Math.min(innerWidth*.5,Number(localStorage.getItem("assistant-width"))||420);historyWidth.value=Number(localStorage.getItem("history-width"))||240;conversations.value=await loadConversations();activeId.value=conversations.value[0]?.id||"";window.addEventListener("attach-event",attach as EventListener)});
onBeforeUnmount(()=>window.removeEventListener("attach-event",attach as EventListener));
</script>
<template>
<button class="assistant-trigger" data-testid="assistant-toggle" :aria-expanded="open" @click="openPanel">提问</button>
<aside v-show="open" class="assistant-panel assistant-workspace" data-testid="global-assistant" :style="{width:panelWidth+'px'}" aria-label="研究助手">
<button class="assistant-resizer" data-testid="assistant-resizer" aria-label="调整助手宽度" @pointerdown="resize($event,'panel')" @keydown="keyResize($event,'panel')" tabindex="0"></button>
<section class="assistant-main"><header class="assistant-panel__header"><div><strong>研究助手</strong><p class="meta">{{ activeScope.snapshot }}</p></div><button class="assistant-close" @click="close">返回</button></header>
<p v-if="storageState.failed" class="error">浏览器存储不可用，当前会话仅保存在内存中。</p>
<div v-if="messages.length" class="assistant-messages" data-testid="conversation-messages" @scroll="atBottom = ($event.target as HTMLElement).scrollHeight - ($event.target as HTMLElement).scrollTop - ($event.target as HTMLElement).clientHeight < 30"><article v-for="(message,index) in messages" :key="message.id" class="conversation-turn" data-testid="conversation-turn" :class="message.role"><p class="meta">{{ message.role==='user'?'你':'助手' }} · {{ message.scope }} · {{ message.mode==='demo'?'模拟':'服务' }}</p><p>{{ message.text }}</p><p v-if="message.attachment" class="meta">依据事件：{{ message.attachment.title }}</p><details v-for="citation in message.citations" :key="citation.index"><summary>[{{ citation.index }}] {{ citation.title }}</summary><p>{{ citation.quote_text }}</p></details></article><button v-if="!atBottom" @click="scrollBottom">回到最新消息</button></div>
<p v-else class="assistant-empty">输入问题开始研究；范围会随本轮记录。</p>
<div class="assistant-composer" data-testid="assistant-composer"><p v-if="attachment" class="assistant-attachment" data-testid="attached-event">下一问依据：{{ attachment.title }} <button @click="removeAttachment">移除</button></p><label>问题<textarea v-model="draft" rows="3" placeholder="输入需要核查的问题" /></label><div class="row"><button class="primary" :disabled="running||!draft.trim()" @click="submit">发送</button><button v-if="running" @click="cancel">取消</button><button data-testid="history-toggle" :aria-expanded="historyOpen" @click="historyOpen=!historyOpen">历史</button></div><p class="meta">{{ status }}</p></div></section>
<aside v-if="historyOpen" class="history-panel" data-testid="history-panel" :style="{width:historyWidth+'px'}"><button class="history-resizer" data-testid="history-resizer" aria-label="调整历史宽度" @pointerdown="resize($event,'history')" @keydown="keyResize($event,'history')" tabindex="0"></button><div class="row"><button data-testid="new-conversation" @click="create">新建</button><button @click="rename">重命名</button></div><button data-testid="history-item" :data-conversation-id="item.id" v-for="item in conversations" :key="item.id" :class="{active:item.id===activeId}" @click="activeId=item.id">{{ item.title }}</button><div class="row"><button @click="remove">删除</button><button @click="exportActive">导出</button></div></aside>
</aside>
</template>