<script setup lang="ts">
import { computed, ref } from "vue";
import { useRoute } from "vue-router";
import { ask, err, type AskResult, type Citation } from "./api";
import { askView } from "./ask-result";
const route=useRoute();const open=ref(false),question=ref(""),running=ref(false),result=ref<AskResult>(),error=ref<ReturnType<typeof err>>(),sources=ref<Citation[]>([]),snapshot=ref("");let controller:AbortController|undefined;const context=computed(()=>route.path==="/ask"?"当前统计范围":"当前动态阅读");
async function submit(){if(!question.value||running.value)return;controller?.abort();controller=new AbortController();running.value=true;result.value=undefined;error.value=undefined;snapshot.value=context.value;try{const response=await ask({question:question.value,filters:{},timezone:"Asia/Shanghai",answer_mode:"concise",client_request_id:crypto.randomUUID()},controller.signal);result.value=response;sources.value=askView(response).citations}catch(cause){if((cause as Error).name!=="AbortError")error.value=err(cause)}finally{running.value=false}}
function cancel(){controller?.abort();running.value=false}
</script>
<template><button class="assistant-trigger" :aria-expanded="open" @click="open=true">提问</button><aside class="assistant-panel" :class="{open}" aria-label="全站助手"><header><strong>研究助手</strong><button @click="open=false">返回</button></header><p class="meta">{{ context }} · 提交后会保留该范围快照。</p><label>问题<textarea v-model="question" class="control" rows="4" placeholder="输入需要核查的问题" /></label><div class="row"><button class="primary" :disabled="running||!question" @click="submit">开始分析</button><button v-if="running" @click="cancel">取消</button></div><p v-if="error" class="error" role="alert">{{ error.code }}：{{ error.message }}</p><section v-if="result" class="assistant-answer"><p class="meta">回答范围：{{ snapshot }}</p><p>{{ result.answer }}</p><details v-for="source in sources" :key="source.index"><summary>[{{ source.index }}] {{ source.title }}</summary><blockquote>{{ source.quote_text||"无段落摘录" }}</blockquote></details></section></aside></template>