<script setup lang="ts">
import { computed, onBeforeUnmount, ref } from "vue";
import { admin, type Source } from "./api";
import { at, adminMessage, type AdminMessage } from "./admin-locale";
import { runProbeQueue } from "./batch-probe-state";
const props = defineProps<{ sources: Source[]; csrf: string; disabled?: boolean }>();
const emit = defineEmits<{ complete: []; unauthorized: []; busy: [boolean] }>();
const selected = ref<string[]>([]), states = ref<Record<string, "pending" | "running" | "success" | "failed" | "skipped">>({}), messages = ref<Record<string, string>>({}), stopped = ref(false), active = ref(false), unmounted = ref(false), summary = ref<AdminMessage>("");
const available = computed(() => props.sources.map((source) => source.id)); const total = computed(() => Object.keys(states.value).length); const done = computed(() => Object.values(states.value).filter((state) => ["success", "failed", "skipped"].includes(state)).length); const percent = computed(() => total.value ? Math.round(done.value / total.value * 100) : 0);
function chooseAll(checked: boolean) { if (!active.value && !props.disabled) selected.value = checked ? [...available.value] : []; }
function toggle(id: string, checked: boolean) { if (!active.value && !props.disabled) selected.value = checked ? [...selected.value, id] : selected.value.filter((value) => value !== id); }
async function probeAll(ids = selected.value) { if (active.value || props.disabled || !ids.length) return; active.value = true; emit("busy", true); stopped.value = false; summary.value = ""; states.value = {}; messages.value = {}; let unauthorized = false; const outcomes = await runProbeQueue(ids, async (id) => admin.probe(props.csrf, id), { concurrency: 2, stopped: () => stopped.value || unmounted.value || unauthorized, unauthorized: () => { unauthorized = true; if (!unmounted.value) emit("unauthorized"); }, onState: (id, state, message) => { if (!unmounted.value) { states.value = { ...states.value, [id]: state }; if (message) messages.value = { ...messages.value, [id]: message }; } } }); if (unmounted.value) return; active.value = false; emit("busy", false); const success = outcomes.filter((x) => x.state === "success").length, failed = outcomes.filter((x) => x.state === "failed").length, skipped = outcomes.filter((x) => x.state === "skipped").length; summary.value = adminMessage("批量探测完成：成功 {success}，失败 {failed}{skipped}。", { success, failed, skipped: skipped ? adminMessage("，跳过 {count}", { count: skipped }) : "" }); if (!unauthorized) emit("complete"); }
onBeforeUnmount(() => { unmounted.value = true; stopped.value = true; });
</script>
<template><details class="card batch-probe" :aria-label="at('批量来源探测')"><summary class="batch-probe__summary"><div><h2>{{ at('批量探测') }}</h2><p class="meta">{{ at('最多同时探测 2 个来源；停止后不会发出尚未开始的请求。') }}</p></div></summary><div class="batch-probe__body"><svg v-if="active" class="batch-progress" viewBox="0 0 36 36" role="img" :aria-label="at('已完成 {done}/{total}', { done, total })"><circle cx="18" cy="18" r="15.5"/><circle cx="18" cy="18" r="15.5" :stroke-dasharray="`${percent} 100`"/><text x="18" y="20.5">{{ done }}/{{ total }}</text></svg><div class="batch-probe__controls"><label><input type="checkbox" :checked="selected.length === available.length && available.length > 0" :disabled="active || disabled" @change="chooseAll(($event.target as HTMLInputElement).checked)" />{{ at('全选') }}</label><button class="admin-action" type="button" :disabled="active || disabled || !selected.length" @click="probeAll()">{{ at('探测选中（{count}）', { count: selected.length }) }}</button><button class="admin-action" type="button" :disabled="active || disabled || !available.length" @click="probeAll(available)">{{ at('探测全部') }}</button><button class="admin-action" v-if="active" type="button" @click="stopped = true">{{ at('停止排队') }}</button></div><div class="batch-probe__list"><label v-for="source in sources" :key="source.id"><input type="checkbox" :checked="selected.includes(source.id)" :disabled="active || disabled" @change="toggle(source.id, ($event.target as HTMLInputElement).checked)" />{{ source.name }}<span v-if="states[source.id]" class="meta" :data-state="states[source.id]"><svg v-if="states[source.id] === 'running'" class="probe-spinner" viewBox="0 0 24 24" :aria-label="at('探测中')"><circle cx="12" cy="12" r="8"/></svg>{{ at({ pending: "等待中", running: "探测中", success: "成功", failed: "失败", skipped: "已跳过" }[states[source.id]]) }} {{ at(messages[source.id] || "") }}</span></label></div><p v-if="summary" class="admin-notice" aria-live="polite">{{ at(summary) }}</p></div></details></template>
<style scoped>
.batch-probe { padding:var(--s4); border-bottom:0; }
.batch-probe__summary { display:flex; align-items:start; justify-content:space-between; gap:16px; cursor:pointer; list-style:none; }
.batch-probe__summary::-webkit-details-marker { display:none; }
.batch-probe__summary::after { content:""; flex:none; width:8px; height:8px; margin:7px 3px 0 0; border-right:2px solid var(--muted); border-bottom:2px solid var(--muted); transform:rotate(45deg); transition:transform .16s ease; }
.batch-probe[open] > .batch-probe__summary::after { transform:rotate(225deg); }
.batch-probe__summary h2 { margin:0; font-size:20px; }
.batch-probe__summary .meta { margin:4px 0 0; }
.batch-probe[open] > .batch-probe__summary { padding-bottom:var(--s3); border-bottom:1px solid var(--line); margin-bottom:var(--s3); }
.batch-probe__body > .batch-progress { float:right; margin-bottom:var(--s2); }
.batch-probe__summary:focus-visible { outline:2px solid var(--blue); outline-offset:4px; border-radius:4px; }
@media (prefers-reduced-motion: reduce) { .batch-probe__summary::after { transition:none; } }
</style>
