<script setup lang="ts">
import { computed, onMounted, ref } from "vue";
import { admin, err, type ProbeResult, type Run, type Source } from "./api";
import BatchProbe from "./BatchProbe.vue";
import AdminArticles from "./AdminArticles.vue";
import "./admin-actions.css";
import { adminRequestGeneration } from "./admin-state";
import { at, adminMessage, adminError, type AdminMessage } from "./admin-locale";
import { formatDate, translate as tr } from "./locale";
import { idempotentSubmission } from "./submission";

const authenticated = ref(false), csrf = ref(""), expiresAt = ref(""), password = ref(""), activeTab = ref<"sources" | "runs">("sources");
const loginLoading = ref(false), loginError = ref<ReturnType<typeof err>>(), notice = ref<AdminMessage>("");
const sources = ref<Source[]>([]), runs = ref<Run[]>([]);
const batchBusy = ref(false), loading = ref(false), actionId = ref(""), pageError = ref<ReturnType<typeof err>>();
const sourceDraft = ref({ name: "", feed_url: "", channel_type: "rss" }), editingId = ref<string | null>(null), editDraft = ref({ name: "", feed_url: "" });
const selectedSourceIds = ref<string[]>([]), submission = idempotentSubmission();
const requests = adminRequestGeneration();
const busy = computed(() => Boolean(actionId.value) || loading.value || batchBusy.value);
const selectableSources = computed(() => sources.value.filter((source) => source.enabled && source.channel_type === "rss"));
const formatTime = (value?: string | null) => formatDate(value, { dateStyle: "short", timeStyle: "short" });
const healthLabel = (value: string) => at(({ healthy: "健康", rate_limited: "受限", unverified: "未验证", degraded: "异常", failed: "失败", unhealthy: "异常", unknown: "未知" }[value.toLowerCase()] ?? at("未知（{value}）", { value })));
const runStatusLabel = (value: string) => at(({ queued: "排队中", partial: "部分完成", completed: "已完成", failed: "失败", running: "进行中", success: "已完成", cancelled: "已取消" }[value.toLowerCase()] ?? "未知状态"));
const runCounts = (run: Run) => at("发现 {found} · 新增文章 {added} · 更新文章 {updated}", { found: run.found, added: run.new_articles, updated: run.updated_articles });
const runErrorLabel = (value?: string | null) => at(!value ? "" : value.includes("403") ? "原站拒绝访问，部分内容未采集。" : value.includes("429") ? "访问频繁，稍后再试。" : value.includes("ConnectError") || value.includes("ConnectTimeout") ? "来源连接失败，请检查服务器到原站的网络。" : "本次采集未完全成功，可在详情查看原始诊断。");
function clearPrivateState() { batchBusy.value = false; csrf.value = ""; expiresAt.value = ""; password.value = ""; sources.value = []; runs.value = []; sourceDraft.value = { name: "", feed_url: "", channel_type: "rss" }; editDraft.value = { name: "", feed_url: "" }; editingId.value = null; selectedSourceIds.value = []; pageError.value = undefined; notice.value = ""; }
function lock(message?: string) { requests.invalidate(); authenticated.value = false; loginLoading.value = false; loading.value = false; actionId.value = ""; clearPrivateState(); if (message) loginError.value = { code: "UNAUTHORIZED", message, status: 401 }; }
function handle(e: unknown, target = pageError) { const problem = err(e); if (problem.status === 401) lock(authenticated.value ? "会话已过期，请重新输入管理口令。" : "管理口令无效。"); else target.value = problem; }
function current(generation: number) { return authenticated.value && requests.current(generation); }
async function restore() { loginLoading.value = true; const generation = requests.capture(); try { const session = await admin.session(); if (!requests.current(generation)) return; authenticated.value = session.authenticated; csrf.value = session.csrf_token ?? ""; expiresAt.value = session.expires_at ?? ""; if (session.authenticated && csrf.value) await loadAll(); } catch (e) { if (requests.current(generation)) handle(e, loginError); } finally { if (requests.current(generation)) loginLoading.value = false; } }
async function login() { if (!password.value || loginLoading.value) return; loginLoading.value = true; loginError.value = undefined; const generation = requests.capture(); try { const session = await admin.session(password.value); password.value = ""; if (!requests.current(generation)) return; if (!session.authenticated || !session.csrf_token) { lock("管理口令无效。"); return; } authenticated.value = true; csrf.value = session.csrf_token; expiresAt.value = session.expires_at ?? ""; await loadAll(); } catch (e) { password.value = ""; if (requests.current(generation)) handle(e, loginError); } finally { if (requests.current(generation)) loginLoading.value = false; } }
async function refreshSources() { if (!authenticated.value) return; const generation = requests.capture(); try { const result = await admin.sources(); if (current(generation)) sources.value = result.items; } catch (e) { if (current(generation)) handle(e); } }
async function loadAll() { if (!authenticated.value) return; loading.value = true; pageError.value = undefined; const generation = requests.capture(); try { const [sourceResult, runResult] = await Promise.all([admin.sources(), admin.runs()]); if (!current(generation)) return; sources.value = sourceResult.items; runs.value = runResult.items; selectedSourceIds.value = selectedSourceIds.value.filter((id) => sourceResult.items.some((source) => source.id === id && source.enabled && source.channel_type === "rss")); } catch (e) { if (current(generation)) handle(e); } finally { if (current(generation)) loading.value = false; } }
async function createSource() { if (busy.value || !sourceDraft.value.name.trim() || !sourceDraft.value.feed_url.trim()) return; actionId.value = "create"; const generation = requests.capture(); try { await admin.createSource(csrf.value, { ...sourceDraft.value, name: sourceDraft.value.name.trim(), feed_url: sourceDraft.value.feed_url.trim() }); if (!current(generation)) return; sourceDraft.value = { name: "", feed_url: "", channel_type: "rss" }; notice.value = "来源已添加，默认处于停用状态。"; await loadAll(); } catch (e) { if (current(generation)) handle(e); } finally { if (current(generation)) actionId.value = ""; } }
function beginEdit(source: Source) { if (!busy.value) { editingId.value = source.id; editDraft.value = { name: source.name, feed_url: source.feed_url }; } }
async function saveSource(source: Source) { if (busy.value) return; actionId.value = `save-${source.id}`; const generation = requests.capture(); try { await admin.updateSource(csrf.value, source.id, editDraft.value); if (!current(generation)) return; editingId.value = null; notice.value = "来源已保存。"; await loadAll(); } catch (e) { if (current(generation)) handle(e); } finally { if (current(generation)) actionId.value = ""; } }
async function toggleSource(source: Source) { if (busy.value) return; actionId.value = `toggle-${source.id}`; const generation = requests.capture(); try { await admin.updateSource(csrf.value, source.id, { enabled: !source.enabled }); if (!current(generation)) return; notice.value = source.enabled ? "来源已停用。" : "来源已启用。"; await loadAll(); } catch (e) { if (current(generation)) handle(e); } finally { if (current(generation)) actionId.value = ""; } }
async function probe(source: Source) { if (busy.value) return; actionId.value = `probe-${source.id}`; const generation = requests.capture(); try { const result: ProbeResult = await admin.probe(csrf.value, source.id); if (!current(generation)) return; notice.value = adminMessage("{name}：{message}{items}", { name: source.name, message: adminMessage(result.message), items: result.items_found === undefined ? "" : adminMessage("（发现 {count} 项）", { count: result.items_found }) }); await refreshSources(); } catch (e) { if (current(generation)) handle(e); } finally { if (current(generation)) actionId.value = ""; } }
function toggleSelection(id: string, checked: boolean) { selectedSourceIds.value = checked ? [...selectedSourceIds.value, id] : selectedSourceIds.value.filter((value) => value !== id); }
async function startIngest() { if (busy.value || !selectedSourceIds.value.length) return; const key = submission.begin(); if (!key) return; actionId.value = "ingest"; const generation = requests.capture(); try { const result = await admin.start(csrf.value, selectedSourceIds.value, key); submission.finish(true); if (!current(generation)) return; notice.value = adminMessage("已接受采集请求：{id}", { id: result.run_id }); const response = await admin.runs(); if (current(generation)) runs.value = response.items; } catch (e) { submission.finish(false); if (current(generation)) handle(e); } finally { if (current(generation)) actionId.value = ""; } }
async function logout() { if (busy.value) return; actionId.value = "logout"; loginError.value = undefined; const generation = requests.capture(); try { await admin.logout(csrf.value); if (!requests.current(generation)) return; lock(); } catch (e) { if (requests.current(generation)) pageError.value = { ...err(e), message: "退出未完成，当前会话仍有效，请重试。" }; } finally { if (requests.current(generation)) actionId.value = ""; } }
onMounted(() => { void restore(); });
</script>
<template>
  <section class="admin-page"><div class="admin-heading"><div><h1 class="page-title">{{ at('管理员后台') }}</h1><p class="page-subtitle">{{ at('管理来源、查看最近收录与采集异常。') }}</p></div><button v-if="authenticated" type="button" class="admin-logout" :title="at('退出管理员后台')" :aria-label="at('退出管理员后台')" :disabled="busy" @click="logout">{{ at(actionId === "logout" ? "退出中…" : "退出") }}</button></div><p v-if="notice" class="admin-notice" aria-live="polite">{{ at(notice) }}</p>
    <section v-if="!authenticated" class="admin-lock card" aria-labelledby="admin-lock-title"><svg viewBox="0 0 24 24" aria-hidden="true"><rect x="5" y="10" width="14" height="10" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3M12 14v2"/></svg><div><h2 id="admin-lock-title">{{ at('需要管理员会话') }}</h2><p class="meta">{{ at('输入管理口令以开启当前浏览器会话。口令不会保存在浏览器存储中。') }}</p></div><form class="admin-login" @submit.prevent="login"><label>{{ at('管理口令') }}<input v-model="password" class="control" type="password" autocomplete="current-password" :disabled="loginLoading" /></label><button class="admin-action" type="submit" :disabled="loginLoading || !password">{{ at(loginLoading ? "验证中…" : "进入后台") }}</button></form><div v-if="loginError" class="error admin-feedback" role="alert">{{ adminError(loginError) }}</div></section>
    <template v-else><p class="meta admin-session">{{ at('会话有效至 {time}。退出或过期后需重新验证。', { time: formatTime(expiresAt) }) }}</p><div class="admin-tabs" role="tablist" :aria-label="at('后台管理区')"><button :class="{ active: activeTab === 'sources' }" role="tab" :aria-selected="activeTab === 'sources'" :disabled="busy" @click="activeTab = 'sources'">{{ at('来源') }}</button><button :class="{ active: activeTab === 'runs' }" role="tab" :aria-selected="activeTab === 'runs'" :disabled="busy" @click="activeTab = 'runs'">{{ at('采集记录') }}</button></div><div v-if="pageError" class="error admin-feedback" role="alert">{{ adminError(pageError) }} <button class="admin-action" type="button" :disabled="busy" @click="loadAll">{{ at('重试') }}</button></div><p v-if="loading" class="admin-skeleton" aria-live="polite">{{ at('正在同步管理数据…') }}</p>
      <section v-if="activeTab === 'sources' && !loading" class="admin-stack" :aria-label="at('来源管理')"><details class="card admin-fold" open><summary class="admin-fold__summary"><div><h2>{{ at('最近采集与异常') }}</h2><p class="meta">{{ at('自动收录无需逐篇审核；失败原因显示在对应记录中。') }}</p></div></summary><div class="admin-fold__body"><button class="admin-action" type="button" :disabled="busy" @click="loadAll">{{ tr('刷新', 'Refresh') }}</button><p v-if="!runs.length" class="meta">{{ tr('暂无采集记录。', 'No collection runs yet.') }}</p><div v-else class="runs-table"><article v-for="run in runs.slice(0, 5)" :key="run.id"><strong>{{ runStatusLabel(run.status) }}</strong><span>{{ formatTime(run.started_at) }}</span><span>{{ runCounts(run) }}</span><details v-if="run.error_summary" class="run-error"><summary>{{ runErrorLabel(run.error_summary) }}</summary><pre>{{ run.error_summary }}</pre></details></article></div></div></details><AdminArticles :csrf="csrf" @unauthorized="lock('会话已过期，请重新输入管理口令。')" /><details class="card admin-fold"><summary class="admin-fold__summary"><div><h2>{{ at('添加 RSS 来源') }}</h2><p class="meta">{{ at('新来源默认停用；探测成功后再开启采集。') }}</p></div></summary><div class="admin-fold__body"><form class="admin-form" @submit.prevent="createSource"><label>{{ at('名称') }}<input v-model="sourceDraft.name" class="control" maxlength="160" :disabled="busy" /></label><label>{{ at('订阅地址') }}<input v-model="sourceDraft.feed_url" class="control" type="url" maxlength="2048" placeholder="https://…/feed.xml" :disabled="busy" /></label><button class="admin-action" type="submit" :disabled="busy || !sourceDraft.name || !sourceDraft.feed_url">{{ at(actionId === "create" ? "添加中…" : "添加来源") }}</button></form></div></details><BatchProbe :sources="sources" :csrf="csrf" :disabled="busy" @busy="batchBusy = $event" @complete="refreshSources" @unauthorized="lock('会话已过期，请重新输入管理口令。')" />
        <details class="card admin-fold"><summary class="admin-fold__summary"><div><h2>{{ at('来源健康') }}</h2><p class="meta">{{ at('{count} 个来源。', { count: sources.length }) }}</p></div></summary><div class="admin-fold__body"><button class="admin-action" type="button" :title="at('刷新来源状态')" :aria-label="at('刷新来源状态')" :disabled="busy" @click="loadAll">{{ at('刷新') }}</button><p v-if="!sources.length" class="empty meta">{{ at('暂无来源。添加一个 RSS 地址后可在此探测和启用。') }}</p><article v-for="source in sources" :key="source.id" class="source-row"><div class="source-main"><template v-if="editingId === source.id"><label>{{ at('名称') }}<input v-model="editDraft.name" class="control" maxlength="160" :disabled="busy" /></label><label>{{ at('订阅地址') }}<input v-model="editDraft.feed_url" class="control" type="url" maxlength="2048" :disabled="busy" /></label></template><template v-else><strong>{{ source.name }}</strong><a :href="source.feed_url" target="_blank" rel="noreferrer">{{ source.feed_url }}</a></template><p class="meta"><span class="health" :class="source.health" :title="healthLabel(source.health)">{{ healthLabel(source.health) }}</span> · {{ at('连续失败 {count} · 最近探测 {checked} · 最近成功 {success}', { count: source.consecutive_failures, checked: formatTime(source.last_checked_at), success: formatTime(source.last_success_at) }) }}<span v-if="source.cooldown_until"> · {{ at('冷却至 {time}', { time: formatTime(source.cooldown_until) }) }}</span></p><p v-if="!source.editable" class="meta">{{ at('内置采集适配：名称和订阅地址由系统维护。') }}</p></div><div class="source-actions"><template v-if="editingId === source.id"><button class="admin-action" type="button" :disabled="busy" @click="saveSource(source)">{{ at(actionId === `save-${source.id}` ? "保存中…" : "保存") }}</button><button class="admin-action" type="button" :disabled="busy" @click="editingId = null">{{ at('取消') }}</button></template><template v-else><button class="admin-action" v-if="source.editable" type="button" :title="at('编辑来源')" :aria-label="at('编辑 {name}', { name: source.name })" :disabled="busy" @click="beginEdit(source)">{{ at('编辑') }}</button><button class="admin-action" type="button" :disabled="busy" :title="at('探测 {name}', { name: source.name })" @click="probe(source)"><svg v-if="actionId === `probe-${source.id}`" class="probe-spinner" viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="8"/></svg>{{ at(actionId === `probe-${source.id}` ? "探测中…" : "探测") }}</button><button class="admin-action" type="button" :disabled="busy" @click="toggleSource(source)">{{ at(source.enabled ? "停用" : "启用") }}</button></template></div></article></div></details></section>
      <section v-if="activeTab === 'runs' && !loading" class="admin-stack"><details class="card admin-fold" open><summary class="admin-fold__summary"><div><h2>{{ at('采集记录') }}</h2><p class="meta">{{ at('手动采集仅提交下方明确勾选的已启用 RSS 来源。归档适配由定时回填处理，不能在此提交。') }}</p></div></summary><div class="admin-fold__body"><button class="admin-action" type="button" :disabled="busy || !selectedSourceIds.length" @click="startIngest">{{ at(actionId === "ingest" ? "提交中…" : "开始采集") }}</button><fieldset class="source-picker"><legend>{{ at('选择要采集的 RSS 来源') }}</legend><p v-if="!selectableSources.length" class="meta">{{ at('没有可手动采集的已启用 RSS 来源。') }}</p><label v-for="source in selectableSources" :key="source.id"><input type="checkbox" :checked="selectedSourceIds.includes(source.id)" :disabled="busy" @change="toggleSelection(source.id, ($event.target as HTMLInputElement).checked)" />{{ source.name }}</label></fieldset><p v-if="!runs.length" class="empty meta">{{ at('尚无采集记录。') }}</p><div v-else class="runs-table"><article v-for="run in runs" :key="run.id"><strong :title="runStatusLabel(run.status)">{{ runStatusLabel(run.status) }}</strong><span>{{ formatTime(run.started_at) }}</span><span class="tabular">{{ runCounts(run) }}</span><span class="tabular">{{ at('解析失败 {parser} · 任务失败 {jobs}', { parser: run.parser_failures, jobs: run.failed_jobs }) }}</span><details v-if="run.error_summary" class="run-error"><summary>{{ runErrorLabel(run.error_summary) }}</summary><pre>{{ run.error_summary }}</pre></details></article></div></div></details></section>
    </template></section>
</template>
<style scoped>
.admin-fold > .admin-fold__summary { display: flex; align-items: start; justify-content: space-between; gap: 16px; cursor: pointer; list-style: none; }
.admin-fold > .admin-fold__summary::-webkit-details-marker { display: none; }
.admin-fold > .admin-fold__summary::after { content: ""; flex: none; width: 8px; height: 8px; margin: 7px 3px 0 0; border-right: 2px solid var(--muted); border-bottom: 2px solid var(--muted); transform: rotate(45deg); transition: transform .16s ease; }
.admin-fold[open] > .admin-fold__summary::after { transform: rotate(225deg); }
.admin-fold > .admin-fold__summary h2 { margin: 0; font-size: 20px; }
.admin-fold > .admin-fold__summary .meta { margin: 4px 0 0; }
.admin-fold[open] > .admin-fold__summary { padding-bottom: var(--s3); border-bottom: 1px solid var(--line); margin-bottom: var(--s3); }
.admin-fold__body > .admin-action:first-child { margin-bottom: var(--s3); }
.admin-fold > .admin-fold__summary:focus-visible { outline: 2px solid var(--blue); outline-offset: 4px; border-radius: 4px; }
@media (prefers-reduced-motion: reduce) { .admin-fold > .admin-fold__summary::after { transition: none; } }
</style>
