param([string]$BaseUrl='http://127.0.0.1:5175')
$ErrorActionPreference='Stop'
$session='radar-mvp'
$checks=[Collections.Generic.List[object]]::new()
function Js([string]$code){$raw=& agent-browser --session $session eval -b ([Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($code)));if($LASTEXITCODE -ne 0){throw $raw};$raw|ConvertFrom-Json}
function Open([string]$path){& agent-browser --session $session open ($BaseUrl+$path)|Out-Null;Js "(async()=>{for(let i=0;i<80;i++){const b=document.querySelector('[data-testid=assistant-toggle]');if(b){b.click();return}await new Promise(r=>setTimeout(r,50))}throw Error('No assistant')})()"|Out-Null}
$setup=@'
const t=id=>document.querySelector('[data-testid="'+id+'"]'), panel=()=>t('global-assistant'), turns=()=>[...panel().querySelectorAll('.conversation-turn.assistant')], last=()=>turns().at(-1), body=()=>panel().innerText;
const pause=ms=>new Promise(r=>setTimeout(r,ms)), until=async f=>{for(let i=0;i<100;i++){if(f())return;await pause(40)}throw Error('Timed out')};
const button=text=>[...panel().querySelectorAll('button')].find(e=>e.textContent.trim()===text);
const fresh=async()=>{t('new-conversation').click();await pause(30)};
const send=async(q='协议回归')=>{const e=panel().querySelector('textarea');e.value=q;e.dispatchEvent(new Event('input',{bubbles:true}));await pause(0);(button('发送')||button('开始分析')).click()};
const mock=(result,status=200)=>{window.__originalFetch??=window.fetch;window.fetch=(url,init)=>String(url).endsWith('/ask')?Promise.resolve(new Response(JSON.stringify(result),{status,headers:{'content-type':'application/json'}})):window.__originalFetch(url,init)};
const result={answer:'合成协议回答 [2]',citations:[{index:2,title:'合成来源二',source_url:'https://example.invalid/two',quote_text:'明确合成段落'}],execution_status:'completed',answer_status:'answered',scope_total:1,retrieved_count:1,summarized_count:1,citation_count:1,coverage:'complete'};
const queryPlan={intent:'structured_summary',filters:{category:'agent_tool',date_from:'2026-09-08',date_to:'2026-09-10',entity_ids:['entity-a','entity-b'],entity_match:'any'},timezone:'Asia/Shanghai',business_date:'2026-09-14',date_until_exclusive:'2026-09-11',constraints_origin:{date:'request_filter'},free_text:'',requires_clarification:false,clarification_candidates:[],warnings:['已采用界面日期，问题中的日期存在冲突'],entity_roles:['subject','product'],data_mode:'fixture',request_id:'synthetic-protocol-plan'};
'@
function Check([string]$name,[string]$code,[string]$layer='synthetic_api_response_browser'){try{$actual=Js ('(async()=>{'+$setup+$code+'})()');$checks.Add([pscustomobject]@{name=$name;layer=$layer;passed=$actual.passed -eq $true;actual=$actual})}catch{$checks.Add([pscustomobject]@{name=$name;layer=$layer;passed=$false;error=$_.Exception.Message})};Write-Output ('Checked '+$name)}
& agent-browser --session $session set viewport 1440 1000|Out-Null
Open '/ask?demo=1'
Check 'actual_demo_stream_completed' "await fresh();await send('演示引用');await until(()=>!button('取消'));return {passed:body().includes('模拟流已完成')&&last().textContent.includes('[2]')&&!last().querySelector('.error')&&last().textContent.includes('完整匹配 1'),text:last().innerText};" 'synthetic_stream_browser'
Check 'citation_focus_unique_index' "const b=[...last().querySelectorAll('button')].find(e=>e.textContent.includes('[2]'));b.click();await pause(40);return {passed:document.activeElement?.id===b.getAttribute('aria-controls')&&last().textContent.includes('合成段落摘录')};" 'synthetic_stream_browser'
Check 'cancel_partial_stream' "await fresh();await send('取消演示');await pause(180);const partial=last().textContent.includes('这是');button('取消').click();await pause(700);return {passed:partial&&body().includes('已取消')&&!body().includes('模拟流已完成')&&!last().textContent.includes('未知 done'),text:last().innerText};" 'synthetic_stream_browser'
Open '/ask'
Check 'json_explicit_index' "await fresh();mock(result);await send();await until(()=>last()?.textContent.includes('合成来源二'));return {passed:body().includes('已完成')&&!last().textContent.includes('[1]')};"
Check 'malformed_citations_error' "await fresh();mock({...result,answer:'不应显示',citations:[{title:'无编号',source_url:'https://example.invalid'}]});await send();await until(()=>last()?.querySelector('.error'));return {passed:last().textContent.includes('引用协议错误')&&!last().textContent.includes('不应显示')};"
Check 'long_untrusted_partial_answer' "await fresh();mock({...result,answer:'<img src=x onerror=alert(1)> '+('长回答 AI-SDK UUID '.repeat(250)),citations:Array.from({length:12},(_,i)=>({index:i+1,title:'合成来源 '+i,source_url:i===0?'javascript:alert(1)':'https://example.invalid/'+i,quote_text:'摘录 '+('q'.repeat(300))})),coverage:'partial'});await send();await until(()=>last()?.querySelectorAll('.evidence-item').length===12);return {passed:!last().querySelector('img')&&!last().querySelector('a[href^=javascript]')&&last().textContent.includes('覆盖不完整')};"
& agent-browser --session $session set viewport 390 600|Out-Null
Check 'long_answer_mobile_geometry' "await pause(100);const c=t('assistant-composer').getBoundingClientRect();return {passed:document.documentElement.scrollWidth<=innerWidth&&c.bottom<=innerHeight+1&&c.top>=0};"
Check 'model_error_plan_retained' "await fresh();mock({code:'MODEL_UNAVAILABLE',message:'模型尚未配置',details:{query_plan_public:queryPlan}},503);await send();await until(()=>last()?.querySelector('[data-testid=query-plan]'));const text=last().innerText;return {passed:!!last().querySelector('.error')&&text.includes('智能体工具')&&text.includes('任一匹配')&&text.includes('起止日期均包含')&&text.includes('已采用界面日期')&&!text.includes('agent_tool')};"
Check 'clarification_plan_retained' "await fresh();mock({code:'CLARIFICATION_REQUIRED',message:'需要澄清',details:{query_plan_public:{...queryPlan,requires_clarification:true,free_text:'未发布的项目',clarification_candidates:[{label:'请指定事件日期',entity_id:null}]}}},422);await send();await until(()=>last()?.textContent.includes('请指定事件日期'));return {passed:last().textContent.includes('未理解限制：未发布的项目')&&!!last().querySelector('.error')};"
Check 'no_answer_message_survives_next_turn' "await fresh();mock({...result,answer:'',citations:[],scope_total:0,answer_status:'no_answer',query_plan_public:queryPlan});await send('无资料问题');await until(()=>!button('取消'));const first=last();mock(result);await send('下一轮');await until(()=>turns().length===2&&!button('取消'));return {passed:first.textContent.includes('没有可回答的资料')&&!!first.querySelector('[data-testid=query-plan]')&&!first.querySelector('.error')};"
Check 'cancel_blocks_late_response' "await fresh();window.fetch=(url,init)=>String(url).endsWith('/ask')?new Promise(resolve=>setTimeout(()=>resolve(new Response(JSON.stringify({code:'MODEL_UNAVAILABLE',message:'晚到错误不应出现',details:{query_plan_public:queryPlan}}),{status:503,headers:{'content-type':'application/json'}})),400)):window.__originalFetch(url,init);await send();await pause(60);button('取消').click();await pause(600);return {passed:body().includes('已取消')&&!last().querySelector('[data-testid=query-plan]')&&!body().includes('晚到错误不应出现')};"
Check 'malformed_plan_keeps_original_error' "await fresh();mock({code:'MODEL_UNAVAILABLE',message:'坏计划原错误仍可见',details:{query_plan_public:{timezone:'UTC',business_date:'2026-09-14',requires_clarification:false,warnings:[]}}},503);await send();await until(()=>last()?.textContent.includes('坏计划原错误仍可见'));return {passed:!last().querySelector('[data-testid=query-plan]')&&!!last().querySelector('.error')};"
Check 'late_rule_preview_cannot_cross_conversation' "await fresh();window.fetch=(url,init)=>String(url).endsWith('/query-plan')?new Promise(resolve=>setTimeout(()=>resolve(new Response(JSON.stringify(queryPlan),{status:200,headers:{'content-type':'application/json'}})),400)):window.__originalFetch(url,init);const e=panel().querySelector('textarea');e.value='规则解析';e.dispatchEvent(new Event('input',{bubbles:true}));await pause(0);button('按问题筛选').click();await pause(50);await fresh();await pause(600);return {passed:turns().length===0&&!body().includes('规则解析预览')};"
$report=[pscustomobject]@{observed_at=[DateTimeOffset]::UtcNow.ToString('o');passed=@($checks|Where-Object passed).Count;total=$checks.Count;checks=$checks}
[IO.File]::WriteAllText([IO.Path]::GetFullPath((Join-Path $PSScriptRoot '../docs/conversation-protocol-results.json')),($report|ConvertTo-Json -Depth 9))
$report|Select-Object passed,total|ConvertTo-Json -Compress
if($report.passed -ne $report.total){exit 1}
