param([string]$BaseUrl='http://127.0.0.1:5175')
$ErrorActionPreference='Stop'
$session='radar-mvp';$checks=[Collections.Generic.List[object]]::new()
function Js([string]$code){$raw=& agent-browser --session $session eval -b ([Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($code)));if($LASTEXITCODE -ne 0){throw $raw};$raw|ConvertFrom-Json}
function Open([string]$path){& agent-browser --session $session open ($BaseUrl+$path)|Out-Null}
$setup=@'
const t=id=>document.querySelector('[data-testid="'+id+'"]'), p=()=>t('global-assistant'), history=()=>t('history-panel');
const pause=ms=>new Promise(r=>setTimeout(r,ms)),until=async f=>{for(let i=0;i<100;i++){if(f())return;await pause(40)}throw Error('Timed out')};
const button=text=>[...p().querySelectorAll('button')].find(e=>e.textContent.trim()===text);
const set=(el,value)=>{el.value=value;el.dispatchEvent(new Event('input',{bubbles:true}))};
const rect=e=>e.getBoundingClientRect();
const within=(inner,outer)=>inner.left>=outer.left-1&&inner.right<=outer.right+1&&inner.top>=outer.top-1&&inner.bottom<=outer.bottom+1;
const visible=e=>!!e&&e.getClientRects().length>0&&getComputedStyle(e).visibility!=='hidden';
const toggleHistory=async()=>{t('history-toggle').click();await pause(80)};
const activeHistory=()=>history()?.querySelector('[data-testid=history-item].active');
const send=async q=>{set(p().querySelector('textarea'),q);await pause(0);button('发送').click();await until(()=>!button('取消'))};
const demoAnswer=()=>{window.__origFetch??=window.fetch;window.fetch=(url,init)=>String(url).endsWith('/ask')?Promise.resolve(new Response(JSON.stringify({answer:'合成测试回答。',citations:[],execution_status:'completed',answer_status:'answered',scope_total:1,retrieved_count:1,summarized_count:1,citation_count:0,coverage:'complete'}),{status:200,headers:{'content-type':'application/json'}})):window.__origFetch(url,init)};
'@
function Check([string]$name,[string]$code){try{$v=Js ('(async()=>{'+$setup+$code+'})()');$checks.Add([pscustomobject]@{name=$name;passed=$v.passed -eq $true;actual=$v})}catch{$checks.Add([pscustomobject]@{name=$name;passed=$false;error=$_.Exception.Message})};Write-Output ('Checked '+$name)}
& agent-browser --session $session set viewport 1440 1000|Out-Null
Open '/'
Check 'initial_composer_is_welcome_state' "await until(()=>t('assistant-toggle'));t('assistant-toggle').click();await until(()=>t('new-conversation'));t('new-conversation').click();await pause(80);window.__initialTop=rect(t('assistant-composer')).top;return {passed:window.__initialTop<innerHeight*.65,top:window.__initialTop};"
Check 'first_send_moves_composer_down' "demoAnswer();await send('布局验收首问');await pause(300);const r=rect(t('assistant-composer'));return {passed:r.top>window.__initialTop+50&&r.bottom<=innerHeight+1,top:r.top};"
Check 'keyboard_actually_changes_width' "const e=t('assistant-resizer');e.focus();const before=rect(p()).width;e.dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowRight',altKey:true,bubbles:true}));await pause(50);const after=rect(p()).width;return {passed:Math.abs(after-before)>=10&&after<=innerWidth/2+1,before,after};"
Check 'pointer_maximum_half_screen' "const e=t('assistant-resizer');e.dispatchEvent(new PointerEvent('pointerdown',{clientX:rect(e).left,clientY:300,bubbles:true}));window.dispatchEvent(new PointerEvent('pointermove',{clientX:0,clientY:300,bubbles:true}));window.dispatchEvent(new PointerEvent('pointerup',{bubbles:true}));await pause(60);return {passed:Math.abs(rect(p()).width-innerWidth/2)<2,width:rect(p()).width};"
Check 'history_visible_and_resizable' "await toggleHistory();const r=rect(history()),outer=rect(p());const e=t('history-resizer');const before=r.width;e.dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowLeft',altKey:true,bubbles:true}));await pause(60);return {passed:within(rect(history()),outer)&&rect(history()).width>=180&&Math.abs(rect(history()).width-before)>=10,history:rect(history()).toJSON(),panel:outer.toJSON()};"
Check 'history_auto_title_and_rename' "const title=activeHistory()?.textContent.trim();const original=window.prompt;window.prompt=()=> '浏览器验收会话';button('重命名').click();window.prompt=original;await pause(60);window.__testId=activeHistory()?.dataset.conversationId;return {passed:title==='布局验收首问'&&activeHistory()?.textContent.trim()==='浏览器验收会话'};"
Check 'export_full_local_conversation' "const original=URL.createObjectURL;window.__exportBlob=undefined;URL.createObjectURL=b=>{window.__exportBlob=b;return original(b)};button('导出').click();URL.createObjectURL=original;const row=JSON.parse(await window.__exportBlob.text());return {passed:row.id===window.__testId&&row.messages.length===2&&row.messages[0].text==='布局验收首问'&&row.messages[1].role==='assistant'};"
Check 'pending_attachment_and_draft_survive_switch' "await toggleHistory();document.querySelector('article.timeline-event a').click();await until(()=>t('attach-event'));t('attach-event').click();await pause(80);window.__attachmentTitle=t('attached-event')?.textContent;set(p().querySelector('textarea'),'保留待发送附件和草稿');await pause(400);t('new-conversation').click();await pause(60);const empty=!t('attached-event')&&!p().querySelector('textarea').value;await toggleHistory();[...history().querySelectorAll('[data-testid=history-item]')].find(e=>e.dataset.conversationId===window.__testId).click();await pause(80);return {passed:empty&&p().querySelector('textarea').value==='保留待发送附件和草稿'&&t('attached-event')?.textContent===window.__attachmentTitle};"
Open '/'
Check 'pending_attachment_and_draft_survive_refresh' "await until(()=>t('assistant-toggle'));t('assistant-toggle').click();await until(()=>p().querySelector('textarea'));await pause(150);return {passed:!!t('attached-event')&&p().querySelector('textarea').value==='保留待发送附件和草稿'};"
Check 'assistant_click_keeps_reader' "document.querySelector('article.timeline-event a').click();await until(()=>t('drawer-event')?.open);await pause(300);p().querySelector('textarea').dispatchEvent(new PointerEvent('pointerdown',{bubbles:true}));p().querySelector('textarea').focus();await pause(60);const d=t('drawer-event');return {passed:d.open&&!d.matches(':modal')&&document.activeElement===p().querySelector('textarea')&&rect(d).right<=rect(p()).left+2};"
Check 'page_background_closes_reader' "document.querySelector('.app-content').dispatchEvent(new PointerEvent('pointerdown',{bubbles:true}));await pause(200);return {passed:!t('drawer-event')?.open&&visible(p())};"
Check 'history_delete_only_selected_test_conversation' "await toggleHistory();const selected=activeHistory()?.dataset.conversationId;button('删除').click();await pause(100);return {passed:![...history().querySelectorAll('[data-testid=history-item]')].some(e=>e.dataset.conversationId===selected)};"
& agent-browser --session $session set viewport 390 600|Out-Null
Check 'mobile_history_full_panel_and_return' "await pause(80);const r=rect(history());const back=[...history().querySelectorAll('button')].find(e=>/返回|收起/.test(e.textContent));const ready=r.width>=innerWidth-2&&within(r,rect(p()))&&!!back;if(back)back.click();await pause(80);return {passed:ready&&!visible(history())&&rect(t('assistant-composer')).bottom<=innerHeight+1,history:r.toJSON()};"
Check 'mobile_event_to_chat_and_back' "document.querySelector('.assistant-close').click();document.querySelector('article.timeline-event a').click();await until(()=>t('attach-event'));t('attach-event').click();await pause(250);const chat=visible(p())&&!document.querySelector('dialog:modal')&&visible(t('attached-event'));const back=[...p().querySelectorAll('button,a')].find(e=>/返回事件|查看事件/.test(e.textContent));if(back)back.click();await pause(250);return {passed:chat&&!!back&&!!document.querySelector('dialog[open]'),chat,returnControl:back?.textContent};"
& agent-browser --session $session press Escape|Out-Null
Open '/ask'
Check 'adopt_week_scope_before_reload' "await until(()=>document.querySelector('[data-testid=insights-summary]'));[...document.querySelectorAll('button')].find(e=>e.textContent.trim()==='近7天').click();await until(()=>document.querySelector('[data-testid=insights-summary]').textContent.includes('精确匹配 25'));t('assistant-toggle').click();await until(()=>t('new-conversation'));t('new-conversation').click();await pause(60);button('采用此页面的新范围')?.click();demoAnswer();await send('范围冻结验收');await pause(400);return {passed:p().querySelector('.assistant-panel__header').textContent.includes('2026-09-08')};"
Open '/ask'
Check 'reload_keeps_frozen_scope_for_next_request' "await until(()=>t('assistant-toggle'));t('assistant-toggle').click();await until(()=>p().querySelector('textarea'));await pause(100);let request;const original=window.fetch;window.fetch=(url,init)=>{if(String(url).endsWith('/ask')){request=JSON.parse(init.body);return Promise.resolve(new Response(JSON.stringify({answer:'合成范围回答',citations:[],execution_status:'completed',answer_status:'answered',scope_total:1,retrieved_count:1,summarized_count:1,citation_count:0,coverage:'complete'}),{status:200,headers:{'content-type':'application/json'}}))}return original(url,init)};await send('刷新后的追问');return {passed:request?.filters.date_from==='2026-09-08'&&request?.filters.date_to==='2026-09-14',filters:request?.filters};"
Open '/'
Check 'storage_failure_visible_memory_usable' "await until(()=>t('assistant-toggle'));t('assistant-toggle').click();await until(()=>t('new-conversation'));const original=IDBFactory.prototype.open;IDBFactory.prototype.open=function(){throw new DOMException('Synthetic blocked storage','SecurityError')};t('new-conversation').click();await pause(250);set(p().querySelector('textarea'),'内存草稿');await pause(100);IDBFactory.prototype.open=original;return {passed:p().innerText.includes('浏览器存储不可用')&&p().querySelector('textarea').value==='内存草稿'};"
$report=[pscustomobject]@{observed_at=[DateTimeOffset]::UtcNow.ToString('o');layer='browser_layout_and_indexeddb_with_synthetic_ask';passed=@($checks|Where-Object passed).Count;total=$checks.Count;checks=$checks}
[IO.File]::WriteAllText([IO.Path]::GetFullPath((Join-Path $PSScriptRoot '../docs/conversation-workspace-results.json')),($report|ConvertTo-Json -Depth 9))
$report|Select-Object passed,total|ConvertTo-Json -Compress
if($report.passed -ne $report.total){exit 1}
