param([string]$BaseUrl = 'http://127.0.0.1:5175')
$ErrorActionPreference = 'Stop'
$session = 'radar-acceptance'
$results = [Collections.Generic.List[object]]::new()
function Js([string]$code) {
    $encoded = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($code))
    $raw = & agent-browser --session $session eval -b $encoded
    if ($LASTEXITCODE -ne 0) { throw "Browser evaluation failed: $raw" }
    return ($raw | ConvertFrom-Json)
}
function Open-Page([string]$path) {
    & agent-browser --session $session open ($BaseUrl + $path) | Out-Null
    if ($LASTEXITCODE -ne 0) { throw "Page unavailable: $path" }
}
function Check([string]$name, [string]$code, [string]$layer = 'fixture_api_browser') {
    try {
        $actual = Js ("(async()=>{const pause=ms=>new Promise(r=>setTimeout(r,ms));const until=async f=>{for(let i=0;i<60;i++){if(f())return;await pause(50);}throw Error('UI state timed out');};const set=(el,v)=>{if(!el)throw Error('Missing control');el.value=v;el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}));};const button=t=>[...document.querySelectorAll('button')].find(e=>e.textContent.trim()===t);const body=()=>document.body.innerText;" + $code + "})()")
        $results.Add([pscustomobject]@{check=$name;layer=$layer;passed=($actual.passed -eq $true);actual=$actual})
    } catch { $results.Add([pscustomobject]@{check=$name;layer=$layer;passed=$false;error=$_.Exception.Message}) }
}
try {
    & agent-browser --session $session set viewport 1440 1000 | Out-Null
    Open-Page '/'
    Check 'home_initial_total_and_page' "await until(()=>body().includes('精确匹配 32 条'));return {passed:document.querySelectorAll('article.timeline-event').length===10};"
    Check 'theme_colors_and_focus_resolve' 'await until(()=>!!document.querySelector(''.pill''));const b=button(''清除'');b.focus();const rgb=x=>(x.match(/[0-9.]+/g)||[]).slice(0,3).map(Number);const lum=x=>rgb(x).map(v=>{v/=255;return v<=0.04045?v/12.92:((v+0.055)/1.055)**2.4}).reduce((a,v,i)=>a+v*[0.2126,0.7152,0.0722][i],0);const ratio=(a,b)=>{const x=lum(a),y=lum(b);return (Math.max(x,y)+0.05)/(Math.min(x,y)+0.05)};const n=getComputedStyle(document.querySelector(''[role=note]'')),p=getComputedStyle(document.querySelector(''.pill'')),f=getComputedStyle(b);const actual={banner:n.backgroundColor,pill:p.backgroundColor,focus:f.outlineColor,noteContrast:ratio(n.color,n.backgroundColor),pillContrast:ratio(p.color,p.backgroundColor),focusContrast:ratio(f.outlineColor,f.backgroundColor),focusWidth:parseFloat(f.outlineWidth)};return {passed:actual.banner!==''rgba(0, 0, 0, 0)''&&actual.pill!==''rgba(0, 0, 0, 0)''&&actual.noteContrast>=4.5&&actual.pillContrast>=4.5&&actual.focusContrast>=3&&actual.focusWidth>=2,actual};'
    Check 'home_pagination_unique_total' "for(const expected of [20,30,32]){await until(()=>!!button('加载更多'));button('加载更多').click();await until(()=>document.querySelectorAll('article.timeline-event').length===expected&&body().includes('精确匹配 32 条'));}const ids=[...document.querySelectorAll('article.timeline-event a')].map(x=>x.pathname);return {passed:ids.length===32&&new Set(ids).size===32&&body().includes('精确匹配 32 条'),count:ids.length};"
    Check 'home_alias_full_dataset_url' "set(document.querySelector('input[placeholder]'),'深度求索');await until(()=>body().includes('精确匹配 6 条'));return {passed:document.querySelectorAll('article.timeline-event').length===6&&new URLSearchParams(location.search).get('q')==='深度求索'};"
    Check 'home_empty_and_clear' "set(document.querySelector('input[placeholder]'),'never-present-synthetic-zz');await until(()=>body().includes('精确匹配 0 条'));const empty=body().includes('这个范围内没有事件');button('清除').click();await until(()=>body().includes('精确匹配 32 条'));return {passed:empty&&document.querySelector('input[placeholder]').value===''};"
    Check 'home_inclusive_date_category_exact_ids' "document.querySelector('input[value=agent_tool]').click();const dates=document.querySelectorAll('input[type=date]');set(dates[0],'2026-09-08');set(dates[1],'2026-09-10');await until(()=>body().includes('精确匹配 3 条'));const ids=[...document.querySelectorAll('article.timeline-event a')].map(x=>x.pathname.split('/').pop()).sort();const want=[13,19,25].map(n=>'00000000-0000-4000-8000-'+String(n).padStart(12,'0'));return {passed:JSON.stringify(ids)===JSON.stringify(want),ids};"
    Check 'home_invalid_dates' "set(document.querySelectorAll('input[type=date]')[0],'2026-09-11');await until(()=>body().includes('日期范围无效'));return {passed:!document.querySelector('article.timeline-event')};"
    foreach ($width in @(390,768,1440)) {
        & agent-browser --session $session set viewport $width 1000 | Out-Null
        if ($width -eq 390) {
            Check 'mobile_navigation_single_line_targets' 'const links=[...document.querySelectorAll(''nav a'')];const rows=links.map(a=>{const tops=[];const walker=document.createTreeWalker(a,NodeFilter.SHOW_TEXT);while(walker.nextNode()){const n=walker.currentNode;if(!n.textContent.trim()||n.parentElement.closest(''svg''))continue;const r=document.createRange();r.selectNodeContents(n);for(const box of r.getClientRects()){if(box.width>0&&!tops.some(t=>Math.abs(t-box.top)<1))tops.push(box.top);}}return {text:a.textContent.trim(),lines:tops.length,height:a.getBoundingClientRect().height};});return {passed:rows.every(x=>x.lines===1&&x.height>=44),rows};'
        }
        Check "home_width_$width" "return {passed:document.documentElement.scrollWidth<=innerWidth,width:innerWidth,scroll:document.documentElement.scrollWidth};"
    }
    Open-Page '/events/00000000-0000-4000-8000-000000000002'
    Check 'detail_saved_version' "await until(()=>body().includes('展开摘录'));const b=[...document.querySelectorAll('button')].find(x=>x.textContent.includes('展开摘录'));b.focus();return {passed:document.activeElement===b};"
    & agent-browser --session $session press Enter | Out-Null
    Check 'detail_keyboard_evidence' "await until(()=>!!document.querySelector('blockquote'));return {passed:body().includes('synthetic-v1-p1')&&body().includes('30000000-0000-4000-8000-000000000001')};"
    Open-Page '/events/00000000-0000-4000-8000-999999999999'
    Check 'detail_unknown_404' "await until(()=>body().includes('事件不存在'));return {passed:!document.querySelector('main article')};"
    Open-Page '/ask'
    Check 'ask_fixture_api_does_not_fake_model' "set(document.querySelector('textarea'),'有哪些进展');await pause(0);button('开始分析').click();await until(()=>!!document.querySelector('.error'));return {passed:!body().includes('模拟回答')&&!document.querySelector('main article'),error:document.querySelector('.error').innerText};"
    Check 'ask_structured_no_answer' "set(document.querySelectorAll('input[type=date]')[0],'2099-01-01');set(document.querySelectorAll('input[type=date]')[1],'2099-01-01');await pause(0);button('开始分析').click();await until(()=>!!document.querySelector('main article'));return {passed:body().includes('没有可回答的资料')&&body().includes('完整匹配 0'),text:document.querySelector('main article').innerText};"
    Check 'ask_real_plan_without_model' 'set(document.querySelector(''textarea''),''DeepSeek'');for(const d of document.querySelectorAll(''input[type=date]''))set(d,'''');await pause(0);button(''开始分析'').click();await pause(0);await until(()=>!!document.querySelector(''[data-testid=query-plan]''));const p=document.querySelector(''[data-testid=query-plan]'').innerText;return {passed:!!document.querySelector(''.error'')&&!document.querySelector(''[data-testid=ask-answer]'')&&p.includes(''1 个实体条件'')&&p.includes(''不限'')&&body().includes(''后端合成数据'')&&body().includes(''未配置''),text:p};' 'fixture_api_browser'
    Open-Page '/ask?demo=1'
    Check 'ask_slow_demo_completed_index' "set(document.querySelector('textarea'),'演示引用');await pause(0);button('开始分析').click();await until(()=>body().includes('模拟流已完成'));const b=[...document.querySelectorAll('main button')].find(x=>x.textContent.includes('[2]'));return {passed:!!b&&!body().includes('[1]')&&body().includes('完整匹配 1')};" 'synthetic_stream_browser'
    Check 'ask_citation_focus' "const b=[...document.querySelectorAll('main button')].find(x=>x.textContent.includes('[2]'));b.click();await until(()=>!!document.querySelector('blockquote'));return {passed:document.activeElement?.id==='citation-2'&&body().includes('合成段落摘录')};" 'synthetic_stream_browser'
    Check 'ask_cancel_partial_no_completion' "await pause(0);button('开始分析').click();await pause(600);const partial=body().includes('这是');button('取消').click();await pause(1150);return {passed:partial&&body().includes('已取消')&&!body().includes('模拟流已完成')};" 'synthetic_stream_browser'
    Open-Page '/ask'
    Check 'ask_real_json_preserves_explicit_index' "const original=window.fetch;window.fetch=(url,init)=>String(url).endsWith('/ask')?Promise.resolve(new Response(JSON.stringify({answer:'引用示例 [2]',citations:[{index:2,title:'来源二',source_url:'https://example.invalid/two',quote_text:'明确段落'}],execution_status:'completed',answer_status:'answered',scope_total:1,retrieved_count:1,summarized_count:1,citation_count:1,coverage:'complete'}),{status:200,headers:{'content-type':'application/json'}})):original(url,init);set(document.querySelector('textarea'),'引用协议检查');await pause(0);button('开始分析').click();await until(()=>body().includes('[2] 来源二'));return {passed:!body().includes('[1]')&&body().includes('已完成')};" 'synthetic_api_response_browser'
    Check 'ask_malformed_citations_fail_visibly' "window.fetch=()=>Promise.resolve(new Response(JSON.stringify({answer:'不应显示',citations:[{title:'无编号',source_url:'https://example.invalid'}],execution_status:'completed',answer_status:'answered',coverage:'complete'}),{status:200,headers:{'content-type':'application/json'}}));button('开始分析').click();await until(()=>!!document.querySelector('.error'));return {passed:body().includes('引用协议错误')&&!document.querySelector('main article')};" 'synthetic_api_response_browser'
    Check 'ask_many_citations_long_untrusted_answer' "window.fetch=()=>Promise.resolve(new Response(JSON.stringify({answer:'<img src=x onerror=alert(1)> '+('长回答 AI-SDK UUID '.repeat(250)),citations:Array.from({length:12},(_,i)=>({index:i+1,title:'长来源标题 '+('SDK-abcdef'.repeat(12)),source_url:i===0?'javascript:alert(1)':'https://example.invalid/'+i,quote_text:'摘录 '+('q'.repeat(300))})),execution_status:'completed',answer_status:'answered',scope_total:100,retrieved_count:20,summarized_count:12,citation_count:12,coverage:'partial'}),{status:200,headers:{'content-type':'application/json'}}));button('开始分析').click();await until(()=>body().includes('覆盖不完整'));return {passed:document.querySelectorAll('main article button').length===12&&!document.querySelector('main img')&&!document.querySelector('a[href^=javascript]')};" 'synthetic_api_response_browser'
    & agent-browser --session $session set viewport 390 1000 | Out-Null
    Check 'ask_long_answer_mobile_overflow' "return {passed:document.documentElement.scrollWidth<=innerWidth,width:innerWidth,scroll:document.documentElement.scrollWidth};" 'synthetic_api_response_browser'
    Open-Page '/ask'
    & agent-browser --session $session set viewport 390 1000 | Out-Null
    Check 'ask_plan_survives_model_unavailable' 'window.__planFixture={"intent":"structured_summary","filters":{"category":"agent_tool","date_from":"2026-09-08","date_to":"2026-09-10","entity_ids":["entity-a","entity-b"],"entity_match":"any"},"timezone":"Asia/Shanghai","business_date":"2026-09-11","date_until_exclusive":"2026-09-11","constraints_origin":{"date":"request_filter"},"free_text":"","requires_clarification":false,"clarification_candidates":[],"warnings":["已采用界面日期，问题中的日期存在冲突"],"entity_roles":["subject","product"],"data_mode":"fixture","request_id":"synthetic-ui-plan"};window.fetch=()=>Promise.resolve(new Response(JSON.stringify({code:''MODEL_UNAVAILABLE'',message:''模型尚未配置'',details:{query_plan_public:window.__planFixture}}),{status:503,headers:{''content-type'':''application/json''}}));set(document.querySelector(''textarea''),''检索范围检查'');await pause(0);button(''开始分析'').click();await until(()=>!!document.querySelector(''[data-testid=query-plan]''));const t=document.querySelector(''[data-testid=query-plan]'').innerText;return {passed:!!document.querySelector(''.error'')&&!document.querySelector(''[data-testid=ask-answer]'')&&t.includes(''智能体工具'')&&t.includes(''起止日期均包含'')&&t.includes(''任一匹配'')&&t.includes(''已采用界面日期'')&&!t.includes(''agent_tool''),text:t};' 'synthetic_api_response_browser'
    Check 'ask_plan_cleared_then_clarified' 'window.fetch=()=>new Promise(resolve=>{window.__resolvePlan=resolve});button(''开始分析'').click();await pause(50);const cleared=!document.querySelector(''[data-testid=query-plan]'');const p={...window.__planFixture,requires_clarification:true,free_text:''未发布的项目'',clarification_candidates:[{label:''请指定事件日期'',entity_id:null}],warnings:[''长约束''+(''abcdefghijklmnop''.repeat(100))]};window.__resolvePlan(new Response(JSON.stringify({code:''CLARIFICATION_REQUIRED'',message:''需要澄清'',details:{query_plan_public:p}}),{status:422,headers:{''content-type'':''application/json''}}));await until(()=>body().includes(''请指定事件日期''));return {passed:cleared&&body().includes(''未理解限制：未发布的项目'')&&!!document.querySelector(''.error'')&&!document.querySelector(''[data-testid=ask-answer]'')&&document.documentElement.scrollWidth<=innerWidth};' 'synthetic_api_response_browser'
    Check 'ask_no_answer_preserves_plan' 'window.fetch=()=>Promise.resolve(new Response(JSON.stringify({answer:'''',citations:[],execution_status:''completed'',answer_status:''no_answer'',scope_total:0,retrieved_count:0,summarized_count:0,citation_count:0,coverage:''complete'',query_plan_public:window.__planFixture}),{status:200,headers:{''content-type'':''application/json''}}));button(''开始分析'').click();await until(()=>!!document.querySelector(''[data-testid=ask-answer]''));return {passed:!!document.querySelector(''[data-testid=query-plan]'')&&!document.querySelector(''.error'')&&body().includes(''没有可回答的资料'')};' 'synthetic_api_response_browser'
    Check 'ask_cancel_blocks_late_plan' 'window.fetch=()=>new Promise(resolve=>setTimeout(()=>resolve(new Response(JSON.stringify({code:''MODEL_UNAVAILABLE'',message:''晚到错误不应出现'',details:{query_plan_public:window.__planFixture}}),{status:503,headers:{''content-type'':''application/json''}})),400));button(''开始分析'').click();await pause(50);button(''取消'').click();await pause(600);return {passed:body().includes(''已取消'')&&!document.querySelector(''[data-testid=query-plan]'')&&!document.querySelector(''[data-testid=ask-answer]'')&&!body().includes(''晚到错误不应出现'')&&!button(''开始分析'').disabled};' 'synthetic_api_response_browser'
    Check 'ask_malformed_plan_retains_error' 'window.fetch=()=>Promise.resolve(new Response(JSON.stringify({code:''MODEL_UNAVAILABLE'',message:''坏计划原错误仍可见'',details:{query_plan_public:{timezone:''UTC'',business_date:''2026-09-11'',requires_clarification:false,warnings:[]}}}),{status:503,headers:{''content-type'':''application/json''}}));button(''开始分析'').click();await until(()=>body().includes(''坏计划原错误仍可见''));return {passed:!document.querySelector(''[data-testid=query-plan]'')&&!!document.querySelector(''.error'')};' 'synthetic_api_response_browser'
    Open-Page '/?demo=1'
    Check 'same_route_switch_demo_to_api' "await until(()=>!!document.querySelector('article.timeline-event'));const before=document.querySelector('article.timeline-event a').getAttribute('href');document.querySelector('a.switch').click();await until(()=>body().includes('后端合成数据'));await pause(600);const after=document.querySelector('article.timeline-event a').getAttribute('href');return {passed:!location.search.includes('demo=1')&&before!==after&&after.endsWith('000000000005'),before,after};"
    Open-Page '/'
    Check 'detail_error_retry_real_request' "await until(()=>!!document.querySelector('article.timeline-event'));const original=window.fetch;let fail=true;window.fetch=(url,init)=>{if(fail&&String(url).includes('/api/v1/events/')){fail=false;return Promise.resolve(new Response(JSON.stringify({code:'RETRIEVAL_FAILED',message:'合成临时故障',retryable:true}),{status:503,headers:{'content-type':'application/json'}}));}return original(url,init);};await document.getElementById('app').__vue_app__.config.globalProperties[String.fromCharCode(36)+'router'].push(document.querySelector('article.timeline-event a').getAttribute('href'));await until(()=>!!document.querySelector('main [role=alert]'));const saw=body().includes('合成临时故障');button('重试').click();await until(()=>!!document.querySelector('main article'));return {passed:saw&&!document.querySelector('main [role=alert]')};" 'synthetic_fault_real_retry_browser'
    Open-Page '/ingest'
    Check 'ingest_independent_source_and_runs_failure' "set(document.querySelector('input[type=password]'),'synthetic-not-a-credential');await pause(0);button('读取状态').click();await until(()=>body().includes('运行服务未配置'));return {passed:body().includes('连续失败')&&button('开始采集').disabled&&localStorage.length===0&&sessionStorage.length===0&&!location.search.includes('synthetic-not-a-credential')};"
    Open-Page '/ingest'
    Check 'ingest_distinct_counts_and_estimated_money' "window.fetch=(url)=>Promise.resolve(new Response(JSON.stringify(String(url).includes('/sources')?{items:[]}:{items:[{id:'90000000-0000-4000-8000-000000000001',status:'partial',found:21,kept:0,candidates:3,versions:2,parser_failures:1,failed_jobs:1,cost:'1.25000',cost_status:'estimated',error_summary:'合成部分失败'}]}),{status:200,headers:{'content-type':'application/json'}}));set(document.querySelector('input[type=password]'),'synthetic-ui-token');await pause(0);button('读取状态').click();await until(()=>body().includes('1.25000'));return {passed:/发现\s*URL\s*21/.test(body())&&/候选报道\s*3/.test(body())&&/正文版本\s*2/.test(body())&&/已发布事件\s*0/.test(body())&&body().includes('估算'),text:body().slice(-600)};" 'synthetic_api_response_browser'
    foreach ($path in @('/events/00000000-0000-4000-8000-000000000002','/ask?demo=1','/ingest')) {
        Open-Page $path
        foreach ($width in @(390,768,1440)) {
            & agent-browser --session $session set viewport $width 1000 | Out-Null
            Check ("page_width_" + $path.Split('?')[0] + "_$width") "await pause(100);return {passed:document.documentElement.scrollWidth<=innerWidth,width:innerWidth,scroll:document.documentElement.scrollWidth};"
        }
    }
} finally {
    $report=[pscustomobject]@{observed_at=[DateTimeOffset]::UtcNow.ToString('o');base_url=$BaseUrl;passed=@($results|Where-Object passed).Count;total=$results.Count;checks=$results}
    [IO.File]::WriteAllText((Join-Path $PSScriptRoot '../docs/frontend-browser-results.json'),($report|ConvertTo-Json -Depth 8))
}
$report | Select-Object passed,total | ConvertTo-Json -Compress
if (@($results|Where-Object { -not $_.passed }).Count) { exit 1 }
