param([string]$BaseUrl='http://127.0.0.1:5175')
$ErrorActionPreference='Stop';$session='radar-mvp';$checks=[Collections.Generic.List[object]]::new()
function Js([string]$code){$out=& agent-browser --session $session eval -b ([Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($code)));if($LASTEXITCODE -ne 0){throw $out};$out|ConvertFrom-Json}
function Open([string]$route){& agent-browser --session $session open ($BaseUrl+$route)|Out-Null}
$setup=@'
const t=id=>document.querySelector('[data-testid="'+id+'"]'),pause=ms=>new Promise(r=>setTimeout(r,ms)),until=async f=>{for(let i=0;i<100;i++){if(f())return;await pause(40)}throw Error('Timed out')},button=text=>[...document.querySelectorAll('button')].find(b=>b.textContent.trim()===text&&b.getClientRects().length>0),rect=e=>e.getBoundingClientRect(),input=(e,value)=>{e.value=value;e.dispatchEvent(new Event('input',{bubbles:true}))};
'@
function Check([string]$name,[string]$code){try{$v=Js ('(async()=>{'+$setup+$code+'})()');$checks.Add([pscustomobject]@{name=$name;passed=$v.passed -eq $true;actual=$v})}catch{$checks.Add([pscustomobject]@{name=$name;passed=$false;error=$_.Exception.Message})};Write-Output $name}
& agent-browser --session $session set viewport 1680 1000|Out-Null
Open '/?demo=1'
Check 'single_calendar_manual_dates' 'await until(()=>t("date-range-trigger"));t("date-range-trigger").click();await pause(100);const native=document.querySelectorAll(".range-popover input[type=date]").length;input(document.querySelector("[name=date_from]"),"2026-09-01");input(document.querySelector("[name=date_to]"),"2026-09-14");await pause(40);t("apply-date-range").click();await pause(550);return {passed:native===0&&location.search.includes("date_from=2026-09-01"),native};'
Check 'day_label_and_independent_collapse' 'const d=t("timeline-day-toggle");const before=document.querySelectorAll(".timeline-event").length;d.click();await pause(60);const closed=d.getAttribute("aria-expanded")==="false"&&document.querySelectorAll(".timeline-event").length<before;const label=d.textContent.trim();d.click();await pause(60);return {passed:closed&&!label.includes("2026")&&label.includes("日")&&document.querySelectorAll(".timeline-event").length===before,label};'
Check 'drawer_shield_blocks_underlying_events' 'const links=[...document.querySelectorAll(".timeline-event__title a")];links[0].click();await until(()=>document.querySelector("dialog[open]"));await pause(100);const r=rect(links[1]),hit=document.elementFromPoint(r.left+5,r.top+5);const shield=hit===t("drawer-shield"),inert=document.querySelector("main").inert;hit.click();await pause(300);return {passed:shield&&inert&&!new URL(location.href).searchParams.get("event")&&!document.querySelector("main").inert,shield,inert};'
Check 'first_send_unfolds_composer_markdown_and_ime' 't("assistant-toggle").click();await pause(100);t("new-conversation").click();await pause(50);const ta=document.querySelector(".assistant-composer textarea");input(ta,"## 第一问\n\n**重点**\n\n- 数据");await pause(40);button("预览").click();await pause(30);const preview=!!document.querySelector(".draft-preview h2");button("继续编辑").click();ta.dispatchEvent(new KeyboardEvent("keydown",{key:"Enter",isComposing:true,bubbles:true,cancelable:true}));await pause(20);const ime=document.querySelectorAll(".conversation-turn").length===0;const start=rect(t("assistant-composer")).top;ta.dispatchEvent(new KeyboardEvent("keydown",{key:"Enter",bubbles:true,cancelable:true}));await pause(60);const middle=rect(t("assistant-composer")).top;await pause(700);const end=rect(t("assistant-composer")).top;return {passed:preview&&ime&&start<middle&&middle<end&&!!document.querySelector(".conversation-turn.user h2")&&document.querySelectorAll(".conversation-turn").length===2,start,middle,end,ime,preview};'
Check 'second_question_pinned_and_history_preserved' 'const ta=document.querySelector(".assistant-composer textarea");input(ta,"**第二问**：统计研究事件");await pause(30);ta.dispatchEvent(new KeyboardEvent("keydown",{key:"Enter",bubbles:true,cancelable:true}));await pause(850);const users=[...document.querySelectorAll(".conversation-turn.user")],v=t("conversation-messages"),offset=rect(users.at(-1)).top-rect(v).top;const preserved=users.length===2&&rect(users[0]).bottom<=rect(v).top;v.dispatchEvent(new WheelEvent("wheel",{bubbles:true}));v.scrollTop=0;await pause(40);const canReadPrevious=rect(users[0]).top>=rect(v).top-1;return {passed:Math.abs(offset)<3&&preserved&&canReadPrevious,offset,preserved,canReadPrevious};'
Check 'scope_compact_in_header_and_adjacent_reader' 'const header=document.querySelector(".assistant-panel__header"),scope=document.querySelector(".assistant-scope-menu"),inside=header.contains(scope);document.querySelector(".timeline-event__title a").click();await until(()=>document.querySelector("dialog[open]"));await pause(80);const d=rect(document.querySelector("dialog[open]")),a=rect(t("global-assistant"));const ta=document.querySelector(".assistant-composer textarea"),r=rect(ta);return {passed:inside&&!document.querySelector(".assistant-scope")&&d.right<=a.left+1&&document.elementFromPoint(r.left+10,r.top+10)===ta,inside,adjacent:d.right<=a.left+1};'
Open '/?demo=1'
Check 'conversation_restores_markdown' 'await until(()=>t("assistant-toggle"));t("assistant-toggle").click();await pause(250);return {passed:document.querySelectorAll(".conversation-turn.user").length===2&&!!document.querySelector(".conversation-turn.user strong")};'
& agent-browser --session $session set viewport 390 844|Out-Null
Open '/?demo=1'
Check 'mobile_calendar_single_and_fit' 'await until(()=>t("date-range-trigger"));const advanced=button("分类与日期 +");if(advanced)advanced.click();await pause(30);t("date-range-trigger").click();await pause(100);const r=rect(t("date-range-popover"));return {passed:r.left>=0&&r.right<=innerWidth&&r.bottom<=innerHeight&&!document.querySelector(".range-popover input[type=date]"),r:r.toJSON()};'
Check 'mobile_assistant_header_composer_and_alignment' 'button("取消").click();t("assistant-toggle").click();await pause(150);t("new-conversation").click();await pause(60);const ta=document.querySelector(".assistant-composer textarea");input(ta,"手机 **第一问**");await pause(30);button("发送").click();await pause(800);input(ta,"手机 **第二问**");await pause(30);button("发送").click();await pause(850);const v=t("conversation-messages"),u=[...document.querySelectorAll(".conversation-turn.user")].at(-1),r=rect(t("assistant-composer"));return {passed:Math.abs(rect(u).top-rect(v).top)<3&&r.bottom<=innerHeight&&r.top>=rect(v).bottom-1&&document.documentElement.scrollWidth<=innerWidth,offset:rect(u).top-rect(v).top,composer:r.toJSON()};'
& agent-browser --session $session fill '#assistant-question' '第一行'|Out-Null
& agent-browser --session $session press Control+Enter|Out-Null
Check 'trusted_control_enter_inserts_newline' 'return {passed:document.querySelector("#assistant-question").value==="第一行\n"};'
& agent-browser --session $session press Enter|Out-Null
Check 'trusted_enter_sends_and_clears' 'await pause(750);return {passed:document.querySelector("#assistant-question").value===""&&[...document.querySelectorAll(".conversation-turn.user")].at(-1).textContent.includes("第一行")};'
$report=[pscustomobject]@{passed=@($checks|Where-Object passed).Count;total=$checks.Count;checks=$checks}
$report|ConvertTo-Json -Depth 8|Set-Content docs/interaction-fixes-browser-results.json
$report|ConvertTo-Json -Depth 6
if($report.passed -ne $report.total){exit 1}
