param([string]$BaseUrl='http://127.0.0.1:5175')
$ErrorActionPreference='Stop';$session='radar-mvp';$checks=[Collections.Generic.List[object]]::new()
function Js([string]$code){$out=& agent-browser --session $session eval -b ([Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($code)));if($LASTEXITCODE -ne 0){throw $out};$out|ConvertFrom-Json}
function Open([string]$route){& agent-browser --session $session open ($BaseUrl+$route)|Out-Null}
$setup=@'
const t=id=>document.querySelector('[data-testid="'+id+'"]'),pause=ms=>new Promise(r=>setTimeout(r,ms)),until=async f=>{for(let i=0;i<100;i++){if(f())return;await pause(40)}throw Error('Timed out')},button=text=>[...document.querySelectorAll('button')].find(b=>b.textContent.trim()===text&&b.getClientRects().length>0),rect=e=>e.getBoundingClientRect(),input=(e,value)=>{e.value=value;e.dispatchEvent(new Event('input',{bubbles:true}))};
'@
function Check([string]$name,[string]$code){try{$v=Js ('(async()=>{'+$setup+$code+'})()');$checks.Add([pscustomobject]@{name=$name;passed=$v.passed -eq $true;actual=$v})}catch{$checks.Add([pscustomobject]@{name=$name;passed=$false;error=$_.Exception.Message})};Write-Output $name}
& agent-browser --session $session set viewport 1680 1000|Out-Null
Open '/?demo=1'
Check 'home_kept_and_new_range_entry' 'await until(()=>t("date-range-trigger"));return {passed:document.querySelector("h1")?.textContent==="AI 动态"&&!document.querySelector(".date-controls>label")&&document.body.innerText.includes("1061")};'
Check 'date_draft_cancel_and_apply' 't("date-range-trigger").click();await until(()=>t("date-range-popover"));document.querySelector("[data-preset=week]").click();await pause(50);const unapplied=!location.search.includes("date_from");button("取消").click();await pause(30);const cancelled=!location.search.includes("date_from");t("date-range-trigger").click();await until(()=>t("date-range-popover"));document.querySelector("[data-preset=month30]").click();t("apply-date-range").click();await until(()=>location.search.includes("date_from"));return {passed:unapplied&&cancelled&&!t("date-range-popover"),url:location.search};'
Check 'category_chip_keyboard_native_semantics' 'const r=document.querySelector("input[type=radio][value=product]");r.click();await pause(450);return {passed:r.checked&&getComputedStyle(r.parentElement).backgroundColor!=="rgba(0, 0, 0, 0)"};'
Open '/ask?demo=1'
Check 'heat_full_aggregate_and_radius' 'await until(()=>button("近30天"));button("近30天").click();await until(()=>document.querySelectorAll(".heat-compact button").length===180);await pause(120);const cells=[...document.querySelectorAll(".heat-compact button")],total=cells.reduce((n,b)=>n+Number(b.textContent),0);return {passed:total===569&&getComputedStyle(cells[0]).borderRadius==="3px",total};'
Check 'heat_drilldown_preserves_corresponding_count' 'const c=[...document.querySelectorAll(".heat-compact button")].find(b=>+b.textContent===5);c.click();await pause(500);return {passed:t("insights-summary").textContent.includes("精确匹配 5 条")&&document.querySelectorAll(".ask-events article").length===5};'
Check 'assistant_resize_never_covers_composer' 't("assistant-toggle").click();await pause(80);t("new-conversation").click();t("history-toggle").click();await pause(100);const edges=[...document.querySelectorAll(".assistant-resizer,.history-resizer")],text=document.querySelector(".assistant-composer textarea"),r=rect(text);return {passed:edges.every(e=>rect(e).width===6)&&document.elementFromPoint(r.left+r.width/2,r.top+15)===text&&rect(t("global-assistant")).width<=innerWidth/2};'
Check 'history_menu_rename_without_prompt' 'document.querySelector("[data-testid=history-more]").click();await until(()=>document.querySelector(".conversation-menu"));button("重命名").click();await until(()=>document.querySelector(".conversation-rename[open]"));input(document.querySelector(".conversation-rename input"),"B 集成验证会话");await pause(20);button("保存").click();await pause(80);return {passed:document.querySelector("[data-testid=history-item]").textContent==="B 集成验证会话"&&!document.querySelector(".conversation-rename[open]")};'
Check 'multi_turn_populated_layout' 'const e=document.querySelector(".assistant-composer textarea");for(const q of ["B 集成连续会话一","B 集成连续会话二"]){input(e,q);await pause(20);button("发送").click();await pause(750)}const turns=[...document.querySelectorAll(".conversation-turn")],messages=rect(t("conversation-messages")),composer=rect(t("assistant-composer"));input(e,"B 集成草稿保留");await pause(100);return {passed:turns.length===4&&turns.every(e=>getComputedStyle(e).position!=="fixed")&&messages.bottom<=composer.top+1&&composer.bottom<=innerHeight};'
Check 'date_escape_keeps_assistant_open' 't("date-range-trigger").click();await until(()=>t("date-range-popover"));document.dispatchEvent(new KeyboardEvent("keydown",{key:"Escape",bubbles:true}));await pause(50);return {passed:!t("date-range-popover")&&getComputedStyle(t("global-assistant")).display!=="none"};'
Check 'reader_left_and_assistant_operable' 'document.querySelector(".ask-events h3 a").click();await until(()=>document.querySelector("dialog[open]"));await pause(100);const d=rect(document.querySelector("dialog[open]")),a=rect(t("global-assistant"));return {passed:d.right<=a.left+1&&d.top<40&&d.height>=innerHeight*.8&&getComputedStyle(document.querySelector("dialog[open]")).position==="fixed"&&!document.querySelector("dialog[open]").matches(":modal"),drawer:d.toJSON(),assistant:a.toJSON()};'
Open '/ask?demo=1'
Check 'existing_indexeddb_reload_restores' 'await until(()=>t("assistant-toggle"));t("assistant-toggle").click();await pause(150);return {passed:document.querySelector(".assistant-composer textarea").value==="B 集成草稿保留"&&document.querySelectorAll(".conversation-turn").length===4};'
& agent-browser --session $session set viewport 390 844|Out-Null
Open '/ask?demo=1'
Check 'mobile_date_and_heat_touch_targets' 'await until(()=>button("近30天"));button("近30天").click();await until(()=>document.querySelectorAll(".heat-compact button").length===180);const heat=rect(document.querySelector(".heat-compact button"));t("date-range-trigger").click();await until(()=>t("date-range-popover"));const cal=rect(document.querySelector(".range-days button")),r=rect(t("date-range-popover"));return {passed:heat.width>=44&&heat.height>=44&&cal.width>=44&&cal.height>=44&&r.right<=innerWidth&&r.bottom<=innerHeight&&document.documentElement.scrollWidth<=innerWidth,heat:heat.toJSON(),calendar:cal.toJSON()};'
Check 'mobile_return_history' 'button("取消").click();t("assistant-toggle").click();await pause(100);t("history-toggle").click();await pause(60);const back=button("返回对话");back.click();await pause(40);return {passed:!!back&&!t("history-panel")&&!!button("返回页面")};'
$report=[pscustomobject]@{passed=@($checks|Where-Object passed).Count;total=$checks.Count;checks=$checks}
$report|ConvertTo-Json -Depth 8|Set-Content docs/compact-integration-browser-results.json
$report|Select-Object passed,total|ConvertTo-Json -Compress
if($report.passed -ne $report.total){exit 1}
