param([string]$BaseUrl = 'http://127.0.0.1:5175', [string]$BrowserSession = 'radar-mvp')
$ErrorActionPreference = 'Stop'
$session = $BrowserSession
$results = [Collections.Generic.List[object]]::new()
function Js([string]$code) {
    $encoded = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($code))
    $raw = & agent-browser --session $session eval -b $encoded
    if ($LASTEXITCODE -ne 0) { throw "Browser evaluation failed: $raw" }
    return ($raw | ConvertFrom-Json)
}
function Open-Page([string]$path) {
    & agent-browser --session $session open ($BaseUrl + $path) | Out-Null
    if ($LASTEXITCODE -ne 0) { throw "Page unavailable: $path" }
}
function Check([string]$name, [string]$code, [string]$layer = 'fixture_api_browser') {
    try {
        $actual = Js ("(async()=>{const pause=ms=>new Promise(r=>setTimeout(r,ms));const until=async f=>{for(let i=0;i<60;i++){if(f())return;await pause(50);}throw Error('UI state timed out');};const set=(el,v)=>{if(!el)throw Error('Missing control');el.value=v;el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}));};const button=t=>[...document.querySelectorAll('button')].find(e=>e.textContent.trim()===t);const body=()=>document.body.innerText;" + $code + "})()")
        $results.Add([pscustomobject]@{check=$name;layer=$layer;passed=($actual.passed -eq $true);actual=$actual})
    } catch { $results.Add([pscustomobject]@{check=$name;layer=$layer;passed=$false;error=$_.Exception.Message}) }
}
try {
    Open-Page '/ask?demo=1'
    Check 'ask_slow_demo_completed_index' "set(document.querySelector('textarea'),'演示引用');await pause(0);button('开始分析').click();await until(()=>body().includes('模拟流已完成'));const b=[...document.querySelectorAll('main button')].find(x=>x.textContent.includes('[2]'));return {passed:!!b&&!body().includes('[1]')&&body().includes('完整匹配 1')};" 'synthetic_stream_browser'
    Check 'ask_citation_focus' "const b=[...document.querySelectorAll('main button')].find(x=>x.textContent.includes('[2]'));b.click();await until(()=>!!document.querySelector('blockquote'));return {passed:document.activeElement?.id==='citation-2'&&body().includes('合成段落摘录')};" 'synthetic_stream_browser'
    Check 'ask_cancel_partial_no_completion' "await pause(0);button('开始分析').click();await pause(600);const partial=body().includes('这是');button('取消').click();await pause(1150);return {passed:partial&&body().includes('已取消')&&!body().includes('模拟流已完成')};" 'synthetic_stream_browser'
    Open-Page '/ask'
    Check 'ask_real_json_preserves_explicit_index' "const original=window.fetch;window.fetch=(url,init)=>String(url).endsWith('/ask')?Promise.resolve(new Response(JSON.stringify({answer:'引用示例 [2]',citations:[{index:2,title:'来源二',source_url:'https://example.invalid/two',quote_text:'明确段落'}],execution_status:'completed',answer_status:'answered',scope_total:1,retrieved_count:1,summarized_count:1,citation_count:1,coverage:'complete'}),{status:200,headers:{'content-type':'application/json'}})):original(url,init);set(document.querySelector('textarea'),'引用协议检查');await pause(0);button('开始分析').click();await until(()=>body().includes('[2] 来源二'));return {passed:!body().includes('[1]')&&body().includes('已完成')};" 'synthetic_api_response_browser'
    Check 'ask_malformed_citations_fail_visibly' "window.fetch=()=>Promise.resolve(new Response(JSON.stringify({answer:'不应显示',citations:[{title:'无编号',source_url:'https://example.invalid'}],execution_status:'completed',answer_status:'answered',coverage:'complete'}),{status:200,headers:{'content-type':'application/json'}}));button('开始分析').click();await until(()=>!!document.querySelector('.ask-question .error'));return {passed:body().includes('引用协议错误')&&!document.querySelector('[data-testid=ask-answer]')};" 'synthetic_api_response_browser'
    Check 'ask_many_citations_long_untrusted_answer' "window.fetch=()=>Promise.resolve(new Response(JSON.stringify({answer:'<img src=x onerror=alert(1)> '+('长回答 AI-SDK UUID '.repeat(250)),citations:Array.from({length:12},(_,i)=>({index:i+1,title:'长来源标题 '+('SDK-abcdef'.repeat(12)),source_url:i===0?'javascript:alert(1)':'https://example.invalid/'+i,quote_text:'摘录 '+('q'.repeat(300))})),execution_status:'completed',answer_status:'answered',scope_total:100,retrieved_count:20,summarized_count:12,citation_count:12,coverage:'partial'}),{status:200,headers:{'content-type':'application/json'}}));button('开始分析').click();await until(()=>body().includes('覆盖不完整'));return {passed:document.querySelectorAll('main article button').length===12&&!document.querySelector('main img')&&!document.querySelector('a[href^=javascript]')};" 'synthetic_api_response_browser'
    & agent-browser --session $session set viewport 390 1000 | Out-Null
    Check 'ask_long_answer_mobile_overflow' "return {passed:document.documentElement.scrollWidth<=innerWidth,width:innerWidth,scroll:document.documentElement.scrollWidth};" 'synthetic_api_response_browser'
    Open-Page '/ask'
    & agent-browser --session $session set viewport 390 1000 | Out-Null
    Check 'ask_plan_survives_model_unavailable' 'window.__planFixture={"intent":"structured_summary","filters":{"category":"agent_tool","date_from":"2026-09-08","date_to":"2026-09-10","entity_ids":["entity-a","entity-b"],"entity_match":"any"},"timezone":"Asia/Shanghai","business_date":"2026-09-11","date_until_exclusive":"2026-09-11","constraints_origin":{"date":"request_filter"},"free_text":"","requires_clarification":false,"clarification_candidates":[],"warnings":["已采用界面日期，问题中的日期存在冲突"],"entity_roles":["subject","product"],"data_mode":"fixture","request_id":"synthetic-ui-plan"};window.fetch=()=>Promise.resolve(new Response(JSON.stringify({code:''MODEL_UNAVAILABLE'',message:''模型尚未配置'',details:{query_plan_public:window.__planFixture}}),{status:503,headers:{''content-type'':''application/json''}}));set(document.querySelector(''textarea''),''检索范围检查'');await pause(0);button(''开始分析'').click();await until(()=>!!document.querySelector(''[data-testid=query-plan]''));const t=document.querySelector(''[data-testid=query-plan]'').innerText;return {passed:!!document.querySelector(''.error'')&&!document.querySelector(''[data-testid=ask-answer]'')&&t.includes(''智能体工具'')&&t.includes(''起止日期均包含'')&&t.includes(''任一匹配'')&&t.includes(''已采用界面日期'')&&!t.includes(''agent_tool''),text:t};' 'synthetic_api_response_browser'
    Check 'ask_plan_cleared_then_clarified' 'window.fetch=()=>new Promise(resolve=>{window.__resolvePlan=resolve});button(''开始分析'').click();await pause(50);const cleared=!document.querySelector(''[data-testid=query-plan]'');const p={...window.__planFixture,requires_clarification:true,free_text:''未发布的项目'',clarification_candidates:[{label:''请指定事件日期'',entity_id:null}],warnings:[''长约束''+(''abcdefghijklmnop''.repeat(100))]};window.__resolvePlan(new Response(JSON.stringify({code:''CLARIFICATION_REQUIRED'',message:''需要澄清'',details:{query_plan_public:p}}),{status:422,headers:{''content-type'':''application/json''}}));await until(()=>body().includes(''请指定事件日期''));return {passed:cleared&&body().includes(''未理解限制：未发布的项目'')&&!!document.querySelector(''.error'')&&!document.querySelector(''[data-testid=ask-answer]'')&&document.documentElement.scrollWidth<=innerWidth};' 'synthetic_api_response_browser'
    Check 'ask_no_answer_preserves_plan' 'window.fetch=()=>Promise.resolve(new Response(JSON.stringify({answer:'''',citations:[],execution_status:''completed'',answer_status:''no_answer'',scope_total:0,retrieved_count:0,summarized_count:0,citation_count:0,coverage:''complete'',query_plan_public:window.__planFixture}),{status:200,headers:{''content-type'':''application/json''}}));button(''开始分析'').click();await until(()=>!!document.querySelector(''[data-testid=ask-answer]''));return {passed:!!document.querySelector(''[data-testid=query-plan]'')&&!document.querySelector(''.error'')&&body().includes(''没有可回答的资料'')};' 'synthetic_api_response_browser'
    Check 'ask_cancel_blocks_late_plan' 'window.fetch=()=>new Promise(resolve=>setTimeout(()=>resolve(new Response(JSON.stringify({code:''MODEL_UNAVAILABLE'',message:''晚到错误不应出现'',details:{query_plan_public:window.__planFixture}}),{status:503,headers:{''content-type'':''application/json''}})),400));button(''开始分析'').click();await pause(50);button(''取消'').click();await pause(600);return {passed:body().includes(''已取消'')&&!document.querySelector(''[data-testid=query-plan]'')&&!document.querySelector(''[data-testid=ask-answer]'')&&!body().includes(''晚到错误不应出现'')&&!button(''开始分析'').disabled};' 'synthetic_api_response_browser'
    Check 'ask_malformed_plan_retains_error' 'window.fetch=()=>Promise.resolve(new Response(JSON.stringify({code:''MODEL_UNAVAILABLE'',message:''坏计划原错误仍可见'',details:{query_plan_public:{timezone:''UTC'',business_date:''2026-09-11'',requires_clarification:false,warnings:[]}}}),{status:503,headers:{''content-type'':''application/json''}}));button(''开始分析'').click();await until(()=>body().includes(''坏计划原错误仍可见''));return {passed:!document.querySelector(''[data-testid=query-plan]'')&&!!document.querySelector(''.error'')};' 'synthetic_api_response_browser'
} finally {
    $report=[pscustomobject]@{observed_at=[DateTimeOffset]::UtcNow.ToString('o');base_url=$BaseUrl;passed=@($results|Where-Object passed).Count;total=$results.Count;checks=$results}
    [IO.File]::WriteAllText((Join-Path $PSScriptRoot '../docs/ask-protocol-browser-results.json'),($report|ConvertTo-Json -Depth 8))
}
$report | Select-Object passed,total | ConvertTo-Json -Compress
if (@($results|Where-Object { -not $_.passed }).Count) { exit 1 }
